language: java
cache:
  directories:
  - $HOME/.m2
notifications: 
  email:
    recipients:
      - email.alexodonovan@gmail.com
    on_success: change
    on_failure: change
after_success:
  - mvn clean test jacoco:report coveralls:report